### ISSUE TITLE
manifest.yml fails with multiple env values

### ISSUE THREAD

**Issue by bitpusher** [cloudfoundry-community/.net-buildpack#23]
builds

```

---
applications:
- name: logsearch-purge-bot
  buildpack: https://github.com/cloudfoundry-community/.net-buildpack
  memory: 256
  instances: 1
  path: ./_bin
  env:
    elasticSearchUrl: "http://ec2-79-125-57-123.eu-west-1.compute.amazonaws.com:9200"
```

fails

```

---
applications:
- name: logsearch-purge-bot
  buildpack: https://github.com/cloudfoundry-community/.net-buildpack
  memory: 256
  instances: 1
  path: ./_bin
  env:
    elasticSearchUrl: "http://ec2-79-125-57-123.eu-west-1.compute.amazonaws.com:9200"
    daysToKeep: "30"
```

```
C:\dev3\logsearch-purge-bot-cloudfoundry>cf push
Time of crash:
  2013-10-21 08:46:39 -0700

Psych::SyntaxError: (C:/dev3/logsearch-purge-bot-cloudfoundry/manifest.yml): found character that cannot start any token while scanning for the next token at line 10 column 1

lib/ruby/1.9.1/psych.rb:203:in `parse'
lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
lib/ruby/1.9.1/psych.rb:151:in `parse'
lib/ruby/1.9.1/psych.rb:127:in `load'
lib/ruby/1.9.1/psych.rb:297:in `block in load_file'
lib/ruby/1.9.1/psych.rb:297:in `open'
lib/ruby/1.9.1/psych.rb:297:in `load_file'
src/lib/manifests/loader/builder.rb:7:in `build'
src/lib/manifests/loader.rb:17:in `manifest'
src/lib/manifests/manifests.rb:55:in `load_manifest'
src/lib/manifests/manifests.rb:17:in `manifest'
src/lib/manifests/plugin.rb:72:in `wrap_push'
src/lib/manifests/plugin.rb:25:in `block in <class:ManifestsPlugin>'
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in `block (2 levels) in invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
src/lib/cf/cli.rb:195:in `block (2 levels) in execute'
src/lib/cf/cli.rb:206:in `save_token_if_it_changes'
src/lib/cf/cli.rb:194:in `block in execute'
src/lib/cf/cli.rb:123:in `wrap_errors'
src/lib/cf/cli.rb:190:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
src/bin/cf:18:in `<main>'

C:\dev3\logsearch-purge-bot-cloudfoundry>
```
